### ISSUE TITLE
Ko positions are not always recognized correctly

### ISSUE THREAD

**Issue by lukas-schneider** [lukas-schneider/torusgo#1] opened 2019-06-03 17:31 UTC
Some positions allow playing on a ko position. For example in the following game state:
`{"ruleSet":{"handicap":2,"komi":5.5,"size":{"x":19,"y":19}},"toMove":2,"board":[0,0,2,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,2,1,0,0,0,0,0,0,0,0,0,0],"koPosition":{"x":19,"y":6},"numPasses":0,"capturedByBlack":10,"capturedByWhite":10}`

**Comment by Vollkornaffe** [comment] 2019-06-03 20:11
asdf

**Comment by Vollkornaffe** [comment] 2019-06-04 07:40
Was caused by not canonizing the KO position.
In the example, x is 19 but should be 0.

5d81a736700b71eea46a512cdcde67ce2adc752d

is fixed now

**Closed by Vollkornaffe** 2019-06-04 07:40 UTC
